#!/usr/bin/env perl
#
# create an index of HTML files generated by HTMLgenerator.pl
#

use File::Spec;


$filetype = "png";
$path_to_images ="graphs/relationships";
$output_directory = "html";

$current_directory = File::Spec->rel2abs('.');


# Get list of images we're working with
opendir(DIR, "$current_directory/$path_to_images") or die $!;
@files = (readdir(DIR));
closedir(DIR);

# Sort them based on their base, not their number or extension
@bases = ();
foreach $file (@files) {
  $fileWithoutExtension = substr $file, 0, rindex($file, ".");
  $base = substr $fileWithoutExtension, 0, rindex($fileWithoutExtension, ".");
  
  next if (grep { $_ eq $base} @bases);
  push @bases, $base;
}



foreach $base (@bases) {
  createHtmlPageForBase($base);
}

# Create Index page
open(INDEX, ">$current_directory/Index.html");

print INDEX "
<html>
  <head>
    <title>Index</title>
  </head>
  
  <body>
    <h1>Index</h1>";

foreach $base (@bases) {
  print INDEX "
    <p><a href=\"$current_directory/$output_directory/$base.0.html\">$base</a></p>";
}


print INDEX "
  </body>
</html>";

  
close(INDEX);


sub createHtmlPageForBase {
  my $base = shift;
  
  # Use a regular expression to count the files that contain $base
  my $num = 0;
  opendir(DIR, "$current_directory/$path_to_images") or die $!;
  foreach $file (readdir(DIR)) {
    $num ++ if($file =~ /$base/);
  }
  closedir(DIR);
  
  mkdir $output_directory;
  
  # Write HTML Files
  my $i = 0;
  for ($i=0; $i < $num; $i++) {
    
    open(HTML, ">$current_directory/$output_directory/$base.$i.html");
    
    my $next = $i + 1;
    my $prev = $i - 1;
    
    $next = 0 if ($i == $num-1);
    $prev = $num-1 if ($i == 0);
    
    print HTML "<html>
    <head>
    <title>$base.$i</title>
    </head>
    <body>
    <h1>$base.$i</h1>
    <!--A link to the index file-->
    <p><a href=\"$current_directory/index.html\">Index</a></p>
    <!--Display the graph, with a link to the next picture-->
    <p><a href=\"$current_directory/$output_directory/$base.$next.html\"><img src=\"$current_directory/$path_to_images/$base.$i.png\"></a></p>
    
    <!--Links to the other graphs in this series-->
    <p>
    <a href=\"$current_directory/$output_directory/$base.$prev.html\">&lt Prev</a>";
    
    for(my $j = 0; $j < $num; $j++) {
      print HTML "
      <a href=\"$current_directory/$output_directory/$base.$j.html\">$j</a>";
    }
    
    print HTML "
    <a href=\"$current_directory/$output_directory/$base.$next.html\">Next &gt</a>
    </p>
    
    </body>
    </html>
    ";
    
    close(HTML);
  }
}

